### ISSUE TITLE
Dataize twise

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eoc#82]
I have the next programm:
```eoc
+alias org.eolang.txt.sprintf

[] > app
  QQ.io.stdout > @
    sprintf
      "Hello, %s"
      "Jeffrey"
```

When I run `eoc dataize app` everything works fine and in the console I can see the next output:
```
Hello, Jeffrey%
```
_(however, it isn't clear, why the program prints `%` at the end)_

Then, I cange the program to the next:

```eoc
+alias org.eolang.txt.sprintf

[] > app
  QQ.io.stdout > @
    sprintf
      "Hello, %s, %d"
      "Jeffrey"
      1
```
and run the same command `eoc dataize app`. Now, in the console I see the next exception:
```java
[ERROR] COMPILATION ERROR :
[ERROR] /Workspace/EOlang/.eoc/generated-sources/EOapp.java:[47,43] cannot find symbol
  symbol:   class EOstring
  location: package EOorg.EOeolang
[ERROR] /Workspace/EOlang/.eoc/generated-sources/EOapp.java:[50,43] cannot find symbol
  symbol:   class EOstring
  location: package EOorg.EOeolang
[ERROR] /Workspace/EOlang/.eoc/generated-sources/EOapp.java:[53,43] cannot find symbol
  symbol:   class EOint
  location: package EOorg.EOeolang
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-cli) on project eoc: Compilation failure: Compilation failure:
[ERROR] /Workspace/EOlang/.eoc/generated-sources/EOapp.java:[47,43] cannot find symbol
[ERROR]   symbol:   class EOstring
[ERROR]   location: package EOorg.EOeolang
[ERROR] /Workspace/EOlang/.eoc/generated-sources/EOapp.java:[50,43] cannot find symbol
[ERROR]   symbol:   class EOstring
[ERROR]   location: package EOorg.EOeolang
[ERROR] /Workspace/EOlang/.eoc/generated-sources/EOapp.java:[53,43] cannot find symbol
[ERROR]   symbol:   class EOint
[ERROR]   location: package EOorg.EOeolang
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-cli) on project eoc: Compilation failure
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:53)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:152)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:76)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1220)
    at org.apache.maven.plugin.compiler.CompilerMojo.execute (CompilerMojo.java:187)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:53)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:152)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:76)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
The command "/Users/lombrozo/.nvm/versions/node/v16.17.1/lib/node_modules/eolang/mvnw/mvnw compiler:compile --quiet -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8 -Deo.targetDir=/Workspace/EOlang/.eoc -Deo.generatedDir=/Workspace/EOlang/.eoc/generated-sources -Deo.version=0.28.10 --errors --batch-mode --update-snapshots --fail-fast" exited with #1 code
```

When I clean `.eoc` folder by `rm -rf .eoc` and run `eoc dataize app` again, in the console I can see:
```
Hello, Jeffrey, 1% 
```
___
I am not sure how it should work, but in `eoc` documentation I haven't found anything about cleaning. Should `eoc` clean `.eoc` folder themself? Correct me please, if I understand the process wrongly and it's a normal behaviour.

**Comment by yegor256** [comment]
@volodya-lombrozo try `eoc clean`. However, it's a bug, we should fix it.

**Comment by yegor256** [comment]
@mximp can you please help?

**Comment by mximp** [comment]
The issue seems to happen when sources are modified and `.eoc` folder already presents: compilation process messes up `./eoc/classes` content. 
I've tried several other apps and got the same error.
`eoc clean` resolves the issue.

**Comment by mximp** [comment]
The root cause is inconsistency between `eoc` and `eo-maven-plugin` in how they work with generated sources:
`transpile` command of `eoc` as a first step removes previously generated sources in `.eoc/generated-sources/`:
```
Previously existed Java sources deleted in .eoc/generated-sources
```
However since transpiled `.xmir` files still present in `.eoc/06-transpile/`, `transpile` goal from `eo-maven-plugin` won't produce new Java source. This results in compilation error.

**Comment by mximp** [comment]
@volodya-lombrozo done. please check and close

**Comment by volodya-lombrozo** [comment]
@mximp It seems working. Thank you.
